### ISSUE TITLE
Showtag doesn't work

### ISSUE THREAD

**Issue by jeppevinkel** [KarlOfDuty/SCPermissions#3]
showtag doesn't work on ranks that have hidden tags by default.
I'm running the server on smod version 3.4.0

**Comment by KarlOfDuty** [comment]
Are you... in the right place?

**Comment by jeppevinkel** [comment]
Yeah. It's on ranks given through this plugin

**Comment by KarlOfDuty** [comment]
Hm, I see. ToggleTag probably runs after this plugin does.

**Comment by jeppevinkel** [comment]
Not sure if related, but I just discovered scperms_removetemprank doesn't remove the vanilla rank, that scperms_givetemprank gave

**Comment by KarlOfDuty** [comment]
Actually do you use the toggletag plugin or just the vanilla command?

**Comment by jeppevinkel** [comment]
I do have the toggletag plugin, but I just noticed I might not have the latest version, so I can try updating and see if that fixes it

**Comment by KarlOfDuty** [comment]
It is unlikely to fix it, I think the rank just isnt loaded yet when the command is ran.

**Comment by KarlOfDuty** [comment]
I think this issue should now be fixed in 1.0.0.
