### ISSUE TITLE
rights are not granted after logging in to the server

### ISSUE THREAD

**Issue by agent188** [KarlOfDuty/SCPermissions#4]
In spite of the correct configuration, I don’t get the rights when entering the server. But when I was on the server and gave myself rights through the scperms_giverank command, the rights were given out, but after the server / round restart they will be lost.

![image](https://user-images.githubusercontent.com/41228098/57981968-42977680-7a47-11e9-9519-236007808639.png)
![image](https://user-images.githubusercontent.com/41228098/57981972-4cb97500-7a47-11e9-8571-8b194dbfc691.png)
![image](https://user-images.githubusercontent.com/41228098/57981977-57740a00-7a47-11e9-8252-d5622969b958.png)
![image](https://user-images.githubusercontent.com/41228098/57981983-5fcc4500-7a47-11e9-8b02-b0dc38f10c96.png)

**Comment by KarlOfDuty** [comment]
I'm very sorry, I completely missed this issue back when you made it and haven't looked at this repo since, the issue has now been fixed in 1.0.0.
