### ISSUE TITLE
global: false not working

### ISSUE THREAD

**Issue by Meibisu** [KarlOfDuty/SCPermissions#6]
scpermissions_config_global: false
scpermissions_playerdata_global: false
not working. Plugin use config from global config directory.

**Comment by iRebbok** [comment]
![image](https://user-images.githubusercontent.com/45738951/60676931-d357d380-9e88-11e9-8178-60b7793a2186.png)
```
scperms_config_global: false
scperms_playerdata_global: false
```

**Comment by Meibisu** [comment]
Thanks, it worked! So this an error in documentation for plugin :C
